// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jibbenracougvyvmumoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppYmJlbnJhY291Z3Z5dm11bW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMDI0ODMsImV4cCI6MjA1ODg3ODQ4M30.9ok9tSxldW-HWEBaxmf_fkT00eAqZEmAY1uT6fqJ8ps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);